# Generated by Django 5.2.5 on 2025-09-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('retraite', 'Retraité'), ('depart', 'Départ')], default='actif', max_length=20)),
                ('date_embauche', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('ufr', models.CharField(max_length=255)),
                ('date_de_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_partenaire', models.CharField(max_length=200)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut_partenariat', models.DateField(blank=True, null=True)),
                ('date_fin_partenariat', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('abreviation_poste', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='phase 1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image_icone', models.ImageField(upload_to='')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_donnee', models.CharField(choices=[('lien', 'Lien'), ('telephone', 'Téléphone')], default='telephone', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_labo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=255)),
                ('diplome', models.CharField(max_length=255)),
                ('annee_obtention', models.DateField()),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurDomaineExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=255)),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurMot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('mot', models.TextField()),
                ('date', models.DateField()),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.domaine')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('extrait', models.CharField(max_length=100)),
                ('phrase_cle', models.CharField(max_length=150)),
                ('contenu_complet', models.TextField()),
                ('date_publication', models.DateField()),
                ('image_principal', models.ImageField(upload_to='')),
                ('statu', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=90)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireParcour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parour', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('description', models.TextField()),
                ('duree_formation', models.IntegerField()),
                ('nombre_etudiant_max', models.IntegerField()),
                ('statu', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=90)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireParcourConditionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('valeur', models.CharField(max_length=255, null=True)),
                ('id_laboratoire_parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoireparcour')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireParcourDeboucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deboucher', models.CharField(max_length=255)),
                ('id_laboratoire_parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoireparcour')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireParcourSpecialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(max_length=255)),
                ('id_laboratoire_parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoireparcour')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoirePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('annee_creation', models.DateField()),
                ('budget_annuel', models.BigIntegerField()),
                ('monnaie', models.CharField(default='FCFA', max_length=20)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoireSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
                ('id_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.page')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoirePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
                ('id_partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
                ('id_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poste')),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheChercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_equipe', models.CharField(choices=[('chef_projet', 'Chef de projet'), ('chercheur_principal', 'Chercheur principal'), ('chercheur_associe', 'Chercheur associé'), ('post_doc', 'Post-doc'), ('etudiant', 'Étudiant')], max_length=30)),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(max_length=255)),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_collaboration', models.CharField(choices=[('Financement', 'Financement'), ('Ressources', 'Ressources'), ('Expertise', 'Expertise'), ('Equipements', 'Equipements'), ('Personnel', 'Personnel')], max_length=255)),
                ('contribution_partenaire', models.CharField(max_length=255, null=True)),
                ('contribution_laboratoire', models.CharField(max_length=255, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_financement', models.BigIntegerField()),
                ('monnaie', models.CharField(default='FCFA', max_length=20)),
                ('id_partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.partenaire')),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheChronologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('etat', models.CharField(choices=[('en cours', 'En cours'), ('termine', 'Terminé'), ('en attente', 'En attente')], max_length=20)),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
                ('id_recherche_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherchephase')),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, null=True)),
                ('annee_publication', models.IntegerField()),
                ('fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('facteur_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('url_publication', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField()),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePublicationCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=255)),
                ('id_recherche_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherchepublication')),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePublicationMotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_cle', models.CharField(max_length=255)),
                ('id_recherche_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherchepublication')),
            ],
        ),
        migrations.CreateModel(
            name='RechercheRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_realisation', models.DateField()),
                ('impact', models.CharField(max_length=255)),
                ('lien_externe', models.URLField()),
                ('id_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recherche')),
            ],
        ),
        migrations.CreateModel(
            name='ChercheurReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordonne', models.CharField(max_length=255)),
                ('id_chercheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chercheur')),
                ('id_reseau_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.reseausocial')),
            ],
            options={
                'verbose_name': 'ChercheurReseau',
                'verbose_name_plural': 'ChercheurReseaux',
            },
        ),
        migrations.CreateModel(
            name='LaboratoireTypeNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laboratoire_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoirenew')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.type')),
            ],
        ),
        migrations.AddField(
            model_name='partenaire',
            name='id_type_partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.typelaboratoire'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='id_type_laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.typelaboratoire'),
        ),
    ]
