# Generated by Django 5.2.5 on 2025-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='logo',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='laboratoirenew',
            name='image_principal',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='image_icone',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
