# Generated by Django 5.2.5 on 2025-09-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_domaine_image_alter_laboratoire_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Termine', 'Terminé')], default='actif', max_length=20),
        ),
    ]
