# Generated by Django 5.2.5 on 2025-09-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_partenaire_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='statut',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='statu',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Termine', 'Terminé')], default='Actif', max_length=20),
        ),
    ]
