# Generated by Django 5.2.5 on 2025-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_partenaire_statut_partenaire_statu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='id_type_partenaire',
            field=models.CharField(choices=[('Académiques et scientifiques', 'Académiques et scientifiques'), ('Institutionnels', 'Institutionnels'), ('Industriels et privés', 'Industriels et privés'), ('Financiers', 'Financiers'), ('Technologiques et d’innovation', 'Technologiques et d’innovation'), ('Associatifs et société civile', 'Associatifs et société civile')], max_length=100),
        ),
    ]
