# Generated by Django 5.2.5 on 2025-09-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_partenaire_id_type_partenaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partenaire',
            old_name='id_type_partenaire',
            new_name='type_partenaire',
        ),
    ]
