# Generated by Django 5.2.5 on 2025-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_id_type_partenaire_partenaire_type_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recherche',
            name='statut',
        ),
        migrations.AddField(
            model_name='recherche',
            name='statu',
            field=models.CharField(choices=[('Planifier', 'Planifiér'), ('En cours', 'En cours'), ('Terminer', 'Terminer'), ('Suspendu', 'Suspendu'), ('Annuler', 'Annuler')], default='Planifier', max_length=20),
        ),
    ]
