# Generated by Django 5.2.5 on 2025-09-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_recherche_statut_recherche_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchelaboratoire',
            name='id_domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.domaine'),
            preserve_default=False,
        ),
    ]
