# Generated by Django 5.2.5 on 2025-09-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_recherchelaboratoire_id_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recherche',
            name='id_domaine',
        ),
    ]
