# Generated by Django 5.2.5 on 2025-09-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_recherche_id_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recherchelaboratoire',
            name='id_domaine',
        ),
        migrations.RemoveField(
            model_name='recherchelaboratoire',
            name='id_laboratoire',
        ),
        migrations.AddField(
            model_name='recherchelaboratoire',
            name='id_laboratoire_domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoiredomaine'),
            preserve_default=False,
        ),
    ]
