# Generated by Django 5.2.5 on 2025-09-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_recherchelaboratoire_id_domaine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recherchepublication',
            name='annee_publication',
        ),
    ]
