# Generated by Django 5.2.5 on 2025-09-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_recherchepublication_annee_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepublication',
            name='fichier',
            field=models.FileField(default='', upload_to='static/documentsPublication/'),
            preserve_default=False,
        ),
    ]
