# Generated by Django 5.2.5 on 2025-09-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_recherchepublication_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheur',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='chercheur',
            name='photo',
            field=models.ImageField(default=1, upload_to='static/photoTeam/'),
            preserve_default=False,
        ),
    ]
