# Generated by Django 5.2.5 on 2025-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_chercheur_photo_url_chercheur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
