# Generated by Django 5.2.5 on 2025-09-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_poste_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
