# Generated by Django 5.2.5 on 2025-09-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_poste_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoirepresentation',
            name='annee_creation',
        ),
        migrations.RemoveField(
            model_name='laboratoirepresentation',
            name='budget_annuel',
        ),
        migrations.RemoveField(
            model_name='laboratoirepresentation',
            name='monnaie',
        ),
        migrations.AddField(
            model_name='laboratoirepresentation',
            name='titre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LaboratoireMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('annee_creation', models.DateField()),
                ('budget_annuel', models.BigIntegerField()),
                ('monnaie', models.CharField(default='FCFA', max_length=20)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoirePresentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/imagePresentation/')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
            ],
        ),
    ]
