# Generated by Django 5.2.5 on 2025-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_laboratoirepresentation_annee_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='statu',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='type_partenaire',
        ),
        migrations.AddField(
            model_name='laboratoirepartenaire',
            name='statu',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Termine', 'Terminé')], default='Actif', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratoirepartenaire',
            name='type_partenaire',
            field=models.CharField(choices=[('Académiques et scientifiques', 'Académiques et scientifiques'), ('Institutionnels', 'Institutionnels'), ('Industriels et privés', 'Industriels et privés'), ('Financiers', 'Financiers'), ('Technologiques et d’innovation', 'Technologiques et d’innovation'), ('Associatifs et société civile', 'Associatifs et société civile')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
