# Generated by Django 5.2.5 on 2025-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_partenaire_statu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(default='', upload_to='static/logoPartenaire/'),
            preserve_default=False,
        ),
    ]
