# Generated by Django 5.2.5 on 2025-09-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_partenaire_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheurlaboratoire',
            name='id_chercheur',
        ),
        migrations.AddField(
            model_name='chercheurlaboratoire',
            name='id_chercheur_poste',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.chercheurposte'),
            preserve_default=False,
        ),
    ]
