# Generated by Django 5.2.5 on 2025-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_chercheurlaboratoire_id_chercheur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheurlaboratoire',
            name='statu',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20),
        ),
    ]
