# Generated by Django 5.2.5 on 2025-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_chercheurlaboratoire_statu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheurreseau',
            name='id_reseau_social',
        ),
        migrations.RemoveField(
            model_name='chercheurreseau',
            name='coordonne',
        ),
        migrations.AddField(
            model_name='chercheurreseau',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chercheurreseau',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chercheurreseau',
            name='type_reseau',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Snapchat', 'Snapchat'), ('ResearchGate', 'ResearchGate'), ('ORCID', 'ORCID'), ('GoogleScholar', 'GoogleScholar'), ('GitHub', 'GitHub'), ('SiteWeb', 'SiteWeb'), ('Email', 'Email'), ('Téléphone', 'Téléphone')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReseauSocial',
        ),
    ]
