# Generated by Django 5.2.5 on 2025-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_chercheurreseau_id_reseau_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheurreseau',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='chercheurreseau',
            name='telephone',
        ),
        migrations.AddField(
            model_name='chercheurreseau',
            name='contact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
