# Generated by Django 5.2.5 on 2025-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_chercheurreseau_lien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='bureau',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
