# Generated by Django 5.2.5 on 2025-09-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_chercheur_bureau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chercheurdomaineexpertise',
            name='nom_domaine',
        ),
        migrations.AddField(
            model_name='chercheurdomaineexpertise',
            name='id_domaine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.domaine'),
            preserve_default=False,
        ),
    ]
