# Generated by Django 5.2.5 on 2025-09-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_chercheur_creer_le_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoireNewAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/AlbumActualite/')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_laboratoire_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoirenew')),
            ],
        ),
    ]
