# Generated by Django 5.2.5 on 2025-09-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_laboratoirenewalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoirePageBlockEntete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire')),
                ('id_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.page')),
            ],
        ),
    ]
