# Generated by Django 5.2.5 on 2025-09-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_laboratoiredomaine_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaine',
            name='image',
        ),
    ]
