# Generated by Django 5.2.5 on 2025-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_domaine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoirenew',
            name='date_publication',
        ),
        migrations.AddField(
            model_name='laboratoirenew',
            name='date_realisation_debut',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='laboratoirenew',
            name='date_realisation_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoiredomaine',
            name='icone',
            field=models.CharField(choices=[('Atom-Science', 'Atom-Science'), ('Dna-Science', 'Dna-Science'), ('Brain-Science', 'Brain-Science'), ('Microscope-Science', 'Microscope-Science'), ('Cpu-Technologie', 'Cpu-Technologie'), ('Leaf-Nature', 'Leaf-Nature'), ('Book-Livre', 'Book-Livre'), ('BookOpen-Livre', 'BookOpen-Livre'), ('Globe-Monde', 'Globe-Monde'), ('Rocket-Science', 'Rocket-Science'), ('Code-Développement', 'Code-Développement'), ('Database-Base de données', 'Database-Base de données'), ('Compass-Orientation', 'Compass-Orientation'), ('PenTool-Outil', 'PenTool-Outil'), ('BarChart-Graphique', 'BarChart-Graphique'), ('PieChart-Graphique', 'PieChart-Graphique'), ('TestTube-Science', 'TestTube-Science'), ('GraduationCap-Éducation', 'GraduationCap-Éducation'), ('Award-Récompense', 'Award-Récompense'), ('Feather-Plume', 'Feather-Plume'), ('Camera-Photo', 'Camera-Photo'), ('Palette-Art', 'Palette-Art'), ('Music-Musique', 'Music-Musique'), ('Calculator-Mathématiques', 'Calculator-Mathématiques'), ('Terminal-Développement', 'Terminal-Développement'), ('Settings-Paramètres', 'Settings-Paramètres'), ('User-Utilisateur', 'User-Utilisateur'), ('Users-Utilisateur', 'Users-Utilisateur'), ('Shield-Sécurité', 'Shield-Sécurité'), ('Zap-Énergie', 'Zap-Énergie')], default='Atom-Science', max_length=50),
        ),
    ]
