# Generated by Django 5.2.5 on 2025-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_laboratoirenew_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoirenew',
            name='date_realisation_debut',
            field=models.DateField(),
        ),
    ]
