# Generated by Django 5.2.5 on 2025-09-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_laboratoirenew_date_realisation_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_candidat', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('prenom_candidat', models.CharField(max_length=255, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('telephone_candidat', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email_candidat', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('adresse_complete', models.TextField(verbose_name='Adresse complète')),
                ('ville_residence', models.CharField(max_length=255, verbose_name='Ville de résidence')),
                ('pays_residence', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('niveau_etude_actuel', models.CharField(choices=[('Licence', 'Licence (Bac+3)'), ('Master 1', 'Master 1 (Bac+4)'), ('Master 2', 'Master 2 (Bac+5)'), ('Doctorat', 'Doctorat (Bac+8)'), ('Autre', 'Autre niveau')], max_length=50, verbose_name="Niveau d'étude actuel")),
                ('etablissement_origine', models.CharField(max_length=255, verbose_name="Établissement d'origine")),
                ('filiere_etude', models.CharField(max_length=255, verbose_name="Filière d'étude")),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne générale (/20)')),
                ('annee_obtention_diplome', models.PositiveIntegerField(verbose_name="Année d'obtention du diplôme")),
                ('cv_candidat', models.FileField(upload_to='static/candidatures/cv/', verbose_name='Curriculum Vitae (PDF)')),
                ('lettre_motivation', models.FileField(upload_to='static/candidatures/lettres/', verbose_name='Lettre de motivation (PDF)')),
                ('releves_notes', models.FileField(upload_to='static/candidatures/notes/', verbose_name='Relevés de notes (PDF)')),
                ('diplome_obtenu', models.FileField(blank=True, null=True, upload_to='static/candidatures/diplomes/', verbose_name='Copie du diplôme (PDF)')),
                ('motivation_principale', models.TextField(blank=True, null=True)),
                ('projet_professionnel', models.TextField(blank=True, null=True)),
                ('attentes_formation', models.TextField(blank=True, null=True)),
                ('statut_candidature', models.CharField(choices=[('En attente', 'En attente de traitement'), ("En cours d'examen", "En cours d'examen"), ('Acceptée', 'Candidature acceptée'), ('Refusée', 'Candidature refusée'), ("Liste d'attente", "En liste d'attente")], default='En attente', max_length=50, verbose_name='Statut de la candidature')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('commentaires_admin', models.TextField(blank=True, help_text='Commentaires internes pour le suivi de la candidature', null=True, verbose_name='Commentaires administratifs')),
                ('note_evaluation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Note d'évaluation (/20)")),
                ('id_parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoireparcour', verbose_name='Parcours demandé')),
            ],
            options={
                'verbose_name': 'Candidature au parcours',
                'verbose_name_plural': 'Candidatures aux parcours',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ContactLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('principal', 'Contact principal'), ('direction', 'Direction'), ('administration', 'Administration'), ('recherche', 'Service recherche'), ('partenariats', 'Partenariats'), ('communication', 'Communication')], default='principal', max_length=30, verbose_name='Type de contact')),
                ('adresse_complete', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('telephone_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal')),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email principal')),
                ('mot_de_passe_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Contact actif')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire', verbose_name='Laboratoire')),
            ],
            options={
                'verbose_name': 'Contact laboratoire',
                'verbose_name_plural': 'Contacts laboratoires',
            },
        ),
        migrations.CreateModel(
            name='HoraireLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('heure_ouverture', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('heure_fermeture', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('est_ferme', models.BooleanField(default=False, verbose_name='Fermé ce jour')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('contact_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contactlaboratoire', verbose_name='Contact laboratoire')),
            ],
            options={
                'verbose_name': 'Horaire laboratoire',
                'verbose_name_plural': 'Horaires laboratoires',
                'ordering': ['contact_laboratoire', 'jour_semaine'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_expediteur', models.CharField(max_length=100, verbose_name="Prénom de l'expéditeur")),
                ('nom_expediteur', models.CharField(max_length=100, verbose_name="Nom de l'expéditeur")),
                ('email_expediteur', models.EmailField(max_length=254, verbose_name="Email de l'expéditeur")),
                ('organisation_expediteur', models.CharField(blank=True, max_length=255, null=True, verbose_name="Organisation de l'expéditeur")),
                ('sujet_message', models.CharField(max_length=255, verbose_name='Sujet du message')),
                ('contenu_message', models.TextField(verbose_name='Contenu du message')),
                ('statut_message', models.CharField(choices=[('nouveau', 'Nouveau message'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut du message')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('reponse_admin', models.TextField(blank=True, null=True, verbose_name='Réponse administrative')),
                ('responsable_reponse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable de la réponse')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('est_traite', models.BooleanField(default=False, verbose_name='Message traité')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.laboratoire', verbose_name='Laboratoire destinataire')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
