# Generated by Django 5.2.5 on 2025-10-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_candidatureparcours_contactlaboratoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='type_contact',
        ),
    ]
