# Generated by Django 5.2.5 on 2025-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_contactlaboratoire_type_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlaboratoire',
            name='type_contact',
            field=models.CharField(choices=[('principal', 'Contact principal')], default='principal', max_length=30, verbose_name='Type de contact'),
        ),
    ]
