# Generated by Django 5.2.5 on 2025-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_contactlaboratoire_type_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='description',
            field=models.CharField(default="Laboratoire de recherche universitaire d'excellence, pionnier dans l'innovation scientifique et technologique depuis plus de 20 ans.", max_length=255),
        ),
    ]
